import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        <div className="flex">
          {/** Sidebar */}
          <div className="hidden md:block h-[100vh] w-[300px]">
            <Sidebar/>
          </div>

          {/** Contents */}
          <div className="p-5 w-full md:max-w-[1140px]">
            {children}
          </div>
        </div>
        {/** Toaster from sonner */}
        <Toaster />
      </body>
    </html>
  );
}
